import type { Metadata } from "next";
import { BackIcon } from "@/components/svgs";

export const metadata: Metadata = {
  title: {
    default: "Default Title",
    absolute: "Post | JSONplaceholder",
    template: "%s | Next Template App",
  },
  description: "Generated by create next app",
};

export default function PostsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mt-8">
      <BackIcon />
      <div>{children}</div>
    </div>
  );
}
